### ISSUE TITLE
the log file created as a link in volumes

### ISSUE THREAD

**Issue by padixa** [aleskxyz/warp-svc#1]
I did use : 

```
volumes:
    - ./warp:/var/lib/cloudflare-warp
```

in docker-compose, and I thought I could check the log but inside of warp folder there is a cfwarp_service_log.txt, it's a link, not a file......

**Comment by aleskxyz** [comment]
yes, I have to do that because warp client generates huge amount of log files that uses disk and cpu.
Those files are pointing to /dev/null to shut up verbose warp!
But you can overwrite those file in your local host directory to a regular file, then you can see logs in files

**Comment by padixa** [comment]
How about give us an option for enable it or disable it. or just add a limit of log size or log days.

**Comment by aleskxyz** [comment]
It seems the problem of huge amount of logs is resolved in new version of warp.
I have updated the image with new version and now you can get logs in the file.
pull the latest docker image
