### ISSUE TITLE
Handle UDP connections

### ISSUE THREAD

**Issue by CXwudi** [aleskxyz/warp-svc#2]
Hi, 

First, thanks for making this docker image. It has been very stable.

However, it looks like so far only TCP connections are handled

https://github.com/aleskxyz/warp-svc/blob/733cedb6e2cad767af62ff613a3becad216eee53/entrypoint.sh#L22

I am not familiar with socat, but with some quick googling, I found that it is possible to let socat to handle both TCP and UDP connection on one port ([ref](https://unix.stackexchange.com/questions/744925/how-to-run-multiple-socat-and-forwarding-both-tcp-and-udp-traffic)), maybe just add one line like `socat udp-listen:1080,reuseaddr,fork udp:localhost:40000 &` ?

**Comment by aleskxyz** [comment]
Hi
Thanks for your kind words!
It seems warp doesn't support udp in proxy mode.
if warp supports udp, then socat will also use it because client side of socks5 proxy is still TCP
