### ISSUE TITLE
Is it possible to add the account and password of SOCKS?

### ISSUE THREAD

**Issue by kokojacket** [aleskxyz/warp-svc#4]
Is it possible to add the account and password of SOCKS?

**Comment by aleskxyz** [comment]
No, it is not provided by warp

**Comment by kokojacket** [comment]
Can it support better IP filtering, there are many IPs that are not available in China, resulting in poor performance

**Comment by aleskxyz** [comment]
> Can it support better IP filtering, there are many IPs that are not available in China, resulting in poor performance

‏The goal of this project is to enable warp to be usable in container environment.
we cannot add features to warp. if warp support something you can use it.
your request is not supported by warp
